[package]
name = "valora"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]

[dependencies]
gfx = "0.16"
gfx_window_glutin = "0.16"
glutin = "0.8"
lyon = "0.8"
error-chain = "0.11"
gfx_device_gl = "0.14.6"